version: '3.8'
services:
  viel:
    container_name: viel_ai
    image: ghcr.io/iteranya/viel-ai:latest
    
    ports:
      - "5666:5666"
    
    volumes:
      - ./bot.db:/app/bot.db
    restart: unless-stopped